server {
    listen 80;
    listen [::]:80;
    server_name krecewm.com *.krecewm.com;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name krecewm.com *.krecewm.com;
    root /var/www/krecewm/public;

    index index.php;

    charset utf-8;

    # SSL Config (se completará automáticamente al correr Let's Encrypt / Certbot)
    # ssl_certificate /etc/letsencrypt/live/krecewm.com/fullchain.pem;
    # ssl_certificate_key /etc/letsencrypt/live/krecewm.com/privkey.pem;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt  { access_log off; log_not_found off; }

    error_page 404 /index.php;

    location ~ \.php$ {
        fastcgi_pass unix:/var/run/php/php8.3-fpm.sock;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        include fastcgi_params;
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }
}
